#!/usr/bin/env bash
# This script displays "Best School" 10 times
# On the 9th iteration, it displays "Best School" and then "Hi"
# on a new line

a=1
while [ "$a" -le 10 ];
do
    if [ "$a" -eq 9 ];
    then
            echo "Best School"
            echo "Hi"
    else
	    echo "Best School"
    fi
    a=$(( a + 1 ))
done
