#!/usr/bin/env bash
# This bash script displays the time for 12 hours and 59 minutes.
# Displays hours from 0 to 12.
# Displays minutes from 1 to 59.
# No using for or until loops.

hours=0
mins=1

while (( hours <= 12 ));
do
  echo "Hour: $hours"
  mins=1

  while (( mins < 60 ));
  do
    echo "$mins"
    mins=$(( mins + 1 ))
  done

  hours=$(( hours + 1 ))
done
