#!/usr/bin/env bash
# This bash script displays:
# The content of the current dir in a list format
# Where only part of the name after the first dash
# is displayed.

dir_list=("$(ls)")
for i in "${dir_list[@]}"; do
  echo "$i" | cut -d '-' -f 2-
done
