#!/usr/bin/env bash
# Appending ServerName to prevent lack of server warnings.
echo "ServerName localhost" >> /etc/apache2.conf

# Start Apache service inside the docker container
service apache2 start
